### ISSUE TITLE
Workflow action ncipollo/release-action omitBodyDuringUpdate

### ISSUE THREAD

**Issue by rodber** [rodber/chevereto-free#117]
Body is being overriden, use:

```yaml
        with:
          allowUpdates: true
          removeArtifacts: true
          omitBodyDuringUpdate: true
```
